In [1]:
import subpackage_1.KNN_data_collection as knn
import subpackage_1.generate_predictions as gp
import numpy as np

SyntaxError: invalid syntax (generate_predictions.py, line 35)

In [2]:
classification_model=knn.KNN('classifier',2)
classification_model.load_csv('Iris.csv','Species')
classification_model.train_test_split(0.4)

Created KNN classifier with k=2!
Dataset successfully loaded!
Successfully completed train/test split!
Training set: 90 samples
Test set: 60 samples


In [ ]:
regression_model=knn.KNN('regressor')
regression_model.load_csv('AutoMPG.csv','mpg')
regression_model.train_test_split(0.33)

In [ ]:
gp.generate_prediction(regression_model,[8,318,150,3436,11],'train')

In [ ]:
gp.generate_prediction(classification_model,[6,3,-3245,102],'train')

In [13]:
result=gp.generate_prediction(classification_model,[4.3,3,1.1,0.1])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [14]:
np.unique(result, return_counts=True)

(array([None], dtype=object), array([1]))

In [16]:
np.unique([1,1,1,1,2])

array([1, 2])

In [6]:
classes,counts=np.unique(['test','Iris-setosa', 'Iris-setosa', 'Iris-setosa','test','hi'],return_counts=True)

In [7]:
counts

array([3, 1, 2])

In [8]:
np.sort(counts)[-2:]

array([2, 3])

In [9]:
classes

array(['Iris-setosa', 'hi', 'test'], dtype='<U11')

In [10]:
counts

array([3, 1, 2])

In [ ]:
if counts>1:
    top_counts=np.sort(counts)[-2:]
    if top_counts[0]==top_counts[1]:
        warnings.warn('Warning: A tie has occurred (top two classes in K nearest neighbors have the same number of occurances). Classification depends on the order of the training data.')